### ISSUE TITLE
Text gets cut off in select if it goes below the baseline

### ISSUE THREAD

**Issue by glortho** [winrox/react-good-input#2]
<img width="314" alt="screen shot 2017-07-25 at 16 08 52" src="https://user-images.githubusercontent.com/526284/28591416-a411b6cc-7153-11e7-99ff-6fd475043838.png">

**Comment by winrox** [comment]
<img width="238" alt="screen shot 2017-07-29 at 2 17 57 pm" src="https://user-images.githubusercontent.com/10481146/28747601-d977201e-7468-11e7-99be-ef96ced6b9b5.png">

I was just going to report this myself. Working on cleaning things up and documenting now.

**Comment by winrox** [comment]
fixed in latest release. closing.
